export { default as Header } from './header/header';
export { default as Main } from './main/main';
export { default as Footer } from './footer/footer';
export { default as AboutHome } from './about/about-home';
export { default as About } from './about/about';
export { default as Contact } from './contact/contact';
export { default as PopularCourse } from './popular-course/popular-course';
export { default as CoursePage } from './course-page/coursePage';
export { default as StatisticDetail } from './statistic-detail/statistic-detail';
